config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "pages#home", as: "root"

  get "/pets", to: "pets#index", as: "pets"
  get "/pets/new", to: "pets#new", as: "new_pet"
  post "/pets", to: "pets#create"
  get "/pets/:id", to: "pets#show", as: "pet"
  get "/pets/:id/edit", to: "pets#edit", as: "edit_pet"
  put "/pets/:id", to: "pets#update"
  patch "/pets/:id", to: "pets#update"
  delete "/pets/:id", to: "pets#destroy"  

  get "/bookings", to: "bookings#index", as: "bookings"
  get "/petsitters/:id/bookings/new", to: "bookings#new", as: "new_booking"
  post "/bookings", to: "bookings#create"
  get "/bookings/:id", to: "bookings#show", as: "booking"
  patch "/bookings/:id/accept", to: "bookings#accept", as: "accept_booking"
  patch "/bookings/:id/reject", to: "bookings#reject", as: "reject_booking"
  get "/bookings/:id/success", to: "bookings#success", as: "success_booking"
  post "/bookings/webhook", to: "bookings#webhook", as: "complete_booking"

  get "/petsitters", to: "petsitters#index", as: "petsitters"
  get "/petsitters/new", to: "petsitters#new", as: "new_petsitter"
  post "/petsitters", to: "petsitters#create"
  get "/petsitters/:id", to: "petsitters#show", as: "petsitter"
  get "/petsitters/:id/edit", to: "petsitters#edit", as: "edit_petsitter"
  put "/petsitters/:id", to: "petsitters#update"
  patch "/petsitters/:id", to: "petsitters#update"
  delete "/petsitters/:id", to: "petsitters#destroy"

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  
  has_many :bookings_pets, dependent: :destroy
  has_many :bookings, through: :bookings_pets

  has_one_attached :picture
  enum pet_type: {
    "small dog":  0,
    "medium dog": 1,
    "large dog":  2,
    "giant dog":  3,
    "puppy":      4,
    "cat":        5,
    "rabbit":     6
  }
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_pet, only: [:show, :edit, :update]

    def index
        # Retrieving only those pets which belong to the logged in user 
        @pets = current_user.pets
    end

    def show

    end

    def edit
        # Retrieving all the possible ENUMS for PET-TYPES
        @pet_types = Pet.pet_types
    end

    def new
        # Assigning @pet the "shape" of a pet active record (no values)
        @pet = Pet.new
        # Retrieving all the possible ENUMS for PET-TYPES
        @pet_types = Pet.pet_types
    end

    def update

        whitelisted_params = pet_params

        if @pet.update(whitelisted_params)
            redirect_to pet_path(params[:id])
        else
            render "edit"
        end

    end

    def create
        whitelisted_params = pet_params

        # Saving into the database all the whitelisted values received by the View
        @pet = current_user.pets.create(whitelisted_params)

        if @pet.errors.any?
            @pet_types = Pet.pet_types
            render "new"
        else
            redirect_to pet_path(@pet)
        end
    end

    def destroy
        # Retrieving id from the view
        id = params[:id]

        # Deleting the specified PET record ID from the database
        Pet.find(id).destroy
        redirect_to pets_path
    end

    private

    def pet_params
        params[:pet][:pet_type] = params[:pet][:pet_type].to_i
        params.require(:pet).permit(:name, :pet_type, :picture)
    end

    def set_pet
        @pet = Pet.find(params[:id])
    end

end

app/views/pets/_form.html.erb
<% if pet.errors.any? %>

    <% for error in pet.errors.full_messages %>
        <p><%=error%></p>
    <% end %>

<% end %>

<%= form_with model: pet, local: true, class: "form" do |form| %>

    <div class="picture-container">

        <% if @pet.picture.attached? %>
            <%= image_tag @pet.picture, id:"picture-preview" %>
        <% else %>
            <%= image_tag "", id:"picture-preview", style:"display: none" %>
        <% end %>

    </div>

    <%= form.label :Upload_Picture %>
    <%= form.file_field :picture, accept: "image/png,image/gif,image/jpeg,image/jpg", onchange: "readURL(this.value)"  %>

    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :pet_type %>
    <%= form.select(:pet_type, options_for_select(pet_types, pet_types[pet.pet_type]))%>

    <%= form.submit %>

<% end %>

<script>
    var readURL = function(event) {

        var input = document.getElementById("pet_picture");
        var fReader = new FileReader();
        fReader.readAsDataURL(input.files[0]);
        fReader.onloadend = function(event){
            var img = document.getElementById("picture-preview");
            img.src = event.target.result;
            img.style.display = "block";
        }

  };
</script>

app/views/pets/edit.html.erb
<main id="pet" class="container">

    <h2 class="page-name">Edit Pet details</h2>

    <%= render "form", pet: @pet, pet_types: @pet_types%>

</main>

app/views/pets/index.html.erb
<main id="pet" class="container">

    <h2 class="page-name">Your Pets</h2>

    <% @pets.each_with_index do |pet, index| %>

        <div class="component">
            <%= link_to(pet) do %>
                <div class="component__image" style="background-image: url('<%= url_for(pet.picture) if pet.picture.attached? %>');">
                </div>
                <div class="component__info">
                    <h3 class="tiny-shadow"><%= pet.name %></h3>
                    <p class="tiny-shadow">(<%= pet.pet_type.capitalize %>)</p>
                </div>
            <% end %>
        </div>
    <% end %>

    <div class="component">
        <%= link_to(new_pet_path) do %>
            <div class="component__new-button">
                <h3 class="tiny-shadow">Add a Pet</h3>
            </div>
        <% end %>
    </div>

</main>

app/views/pets/new.html.erb
<main id="pet" class="container">

    <h2 class="page-name">Add a Pet</h2>

    <%= render "form", pet: @pet, pet_types: @pet_types%>

</main>

app/views/pets/show.html.erb
<main id="pet" class="container">

    <h2 class="page-name">Pet details</h2>

    <div class="form">
    
        <div class="picture-container">

            <% if @pet.picture.attached? %>
                <%= image_tag @pet.picture, id:"picture-preview" %>
            <% else %>
                <%= image_tag "", id:"picture-preview", style:"display: none" %>
            <% end %>

        </div>

        <p>Pet name: <%= @pet.name %></p>

        <p>Pet Type: <%= @pet.pet_type %></p>

        <p>Owner: <%= @pet.user.first_name + " " + @pet.user.last_name %></p>

        <p>Total Bookings: <%= @pet.bookings.where(status:"completed").count %></p>
        
        <%= link_to "Edit", edit_pet_path(@pet.id), class: "link-button" %>

        <%= link_to "Delete", pet_path(@pet.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-button"%>


    </div>

</main>