config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "pages#home", as: "root"

  get "/pets", to: "pets#index", as: "pets"
  get "/pets/new", to: "pets#new", as: "new_pet"
  post "/pets", to: "pets#create"
  get "/pets/:id", to: "pets#show", as: "pet"
  get "/pets/:id/edit", to: "pets#edit", as: "edit_pet"
  put "/pets/:id", to: "pets#update"
  patch "/pets/:id", to: "pets#update"
  delete "/pets/:id", to: "pets#destroy"  

  get "/bookings", to: "bookings#index", as: "bookings"
  get "/petsitters/:id/bookings/new", to: "bookings#new", as: "new_booking"
  post "/bookings", to: "bookings#create"
  get "/bookings/:id", to: "bookings#show", as: "booking"
  patch "/bookings/:id/accept", to: "bookings#accept", as: "accept_booking"
  patch "/bookings/:id/reject", to: "bookings#reject", as: "reject_booking"
  get "/bookings/:id/success", to: "bookings#success", as: "success_booking"
  post "/bookings/webhook", to: "bookings#webhook", as: "complete_booking"

  get "/petsitters", to: "petsitters#index", as: "petsitters"
  get "/petsitters/new", to: "petsitters#new", as: "new_petsitter"
  post "/petsitters", to: "petsitters#create"
  get "/petsitters/:id", to: "petsitters#show", as: "petsitter"
  get "/petsitters/:id/edit", to: "petsitters#edit", as: "edit_petsitter"
  put "/petsitters/:id", to: "petsitters#update"
  patch "/petsitters/:id", to: "petsitters#update"
  delete "/petsitters/:id", to: "petsitters#destroy"

end

app/models/petsitter.rb
class Petsitter < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :petsitters_services
  has_many :services, through: :petsitters_services, dependent: :destroy
  enum status: { active: 1, inactive: 0 }
end

app/controllers/petsitters_controller.rb
class PetsittersController < ApplicationController

    before_action :authenticate_user!, except: [:index]
    before_action :set_petsitter, only: [:show, :edit, :update]

    def index
        if current_user
            # If a user is logged in, make sure to exclude himself from the potential pet-sitters
            @petsitters = Petsitter.where.not(user_id: current_user.id)
        else
            # If a user is not logged in, we cannot identify whether or not this user is an pet-sitter
            @petsitters = Petsitter.all
        end
    end

    def show

    end

    def edit

    end

    def new

        if current_user.petsitter.nil?
            @petsitter = Petsitter.new
            # Assigning the user_id is just to allow showing the user picture in the "new" html page
            @petsitter.user_id = current_user.id
        else
            #render "edit"
            redirect_to petsitter_path(current_user.petsitter)
        end

    end

    def update

        whitelisted_params = petsitter_params

        if @petsitter.update(whitelisted_params)
            redirect_to petsitter_path(params[:id])
        else
            render "edit"
        end

    end

    def create
        whitelisted_params = petsitter_params
        # Create a new petsitter record (using information and FK generated by current_user)
        @petsitter = current_user.create_petsitter(whitelisted_params)

        if @petsitter.errors.any?
            render "new"
        else
            redirect_to petsitter_path(@petsitter)
        end
    end

    def destroy
        id = params[:id]
        Petsitter.find(id).destroy
        redirect_to petsitters_path
    end

    private

    def petsitter_params
        params[:petsitter][:status] = params[:petsitter][:status].to_i
        params.require(:petsitter).permit(:price_rate, :status)
    end

    def set_petsitter
        @petsitter = Petsitter.find(params[:id])
    end

end

app/views/petsitters/_form.html.erb
<% if petsitter.errors.any? %>

    <% for error in petsitter.errors.full_messages %>
        <p><%=error%></p>
    <% end %>

<% end %>

<%= form_with model: petsitter, local: true, class: "form" do |form| %>

    <div class="picture-container">

        <% if @petsitter.user.picture.attached? %>
            <%= image_tag @petsitter.user.picture, id:"picture-preview" %>
        <% else %>
            <%= image_tag "", id:"picture-preview", style:"display: none" %>
        <% end %>

    </div>

    <p>Profile Picture can be modified from <%= link_to "Your Detailes", edit_user_registration_path, class: "standard-link" %></p>

    <%= form.label :price_rate, "Price in cents" %>
    <%= form.number_field :price_rate, min: 0, required:true %>

    <div class="checkbox-list">
        <%= form.label :status, "Available for booking" %>
        <%= form.check_box :status, checked: @petsitter.status == "active" ? true : false %>
    </div>

    <%= form.submit class: "link-button" %>

<% end %>

app/views/petsitters/edit.html.erb
<main id="petsitter" class="container">

    <h2 class="page-name">Edit your Petsitter profile</h2>

    <%= render "form", petsitter: @petsitter %>

</main>

app/views/petsitters/index.html.erb
<main id="petsitter" class="container">

    <h2 class="page-name">Petsitters</h2>

    <% @petsitters.each_with_index do |petsitter, index| %>

        <div class="component">
            <%= link_to(petsitter) do %>
                <div class="component__image" style="background-image: url('<%= url_for(petsitter.user.picture) if petsitter.user.picture.attached? %>');">
                </div>
                <div class="component__info">
                    <p class="tiny-shadow"><%= petsitter.user.first_name + " " + petsitter.user.last_name %></p>
                    <p class="tiny-shadow"><%= number_to_currency(petsitter.price_rate/100.0) %></p>
                </div>
            <% end %>
        </div>
    <% end %>

</main>

app/views/petsitters/new.html.erb
<main id="pet" class="container">

    <h2 class="page-name">Create your Petsitter profile</h2>

    <%= render "form", petsitter: @petsitter %>

</main>

app/views/petsitters/show.html.erb
<main id="petsitter" class="container">

    <h2 class="page-name">Petsitter details</h2>

    <div class="form">
    
        <div class="picture-container">

            <% if @petsitter.user.picture.attached? %>
                <%= image_tag @petsitter.user.picture, id:"picture-preview" %>
            <% else %>
                <%= image_tag "", id:"picture-preview", style:"display: none" %>
            <% end %>

        </div>

        <p>First name: <%= @petsitter.user.first_name %></p>

        <p>Last name: <%= @petsitter.user.last_name %></p>

        <p>Daily Rate: <%= number_to_currency(@petsitter.price_rate/100.0) %></p>
        
        <p>Status: <%= @petsitter.status %></p>

        <p>Total Bookings: <%= @petsitter.bookings.where(status:"completed").count %></p>
        
        <% if current_user.id == @petsitter.user_id %> 

            <%= link_to "Edit", edit_petsitter_path(@petsitter.id), class: "link-button" %>

            <%= link_to "Delete", petsitter_path(@petsitter.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-button"%>

         <% else %>

            <%= link_to "Request a booking", new_booking_path(@petsitter.id), class: "link-button" %>

        <% end %>

    </div>

    <% if @petsitter.user.pets.count > 0 %>

        <h2 class="page-name">Petsitter's Residential Pets</h2>
        <div class="pet-container">
            <% @petsitter.user.pets.each_with_index do |pet, index| %>

                <div class="picture-container">

                    <% if pet.picture.attached? %>
                        <%= image_tag pet.picture, id:"picture-preview" %>
                    <% else %>
                        <%= image_tag "", id:"picture-preview", style:"display: none" %>
                    <% end %>

                </div>

            <% end %>

        </div>

    <% end %>


</main>