config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "pages#home", as: "root"

  get "/pets", to: "pets#index", as: "pets"
  get "/pets/new", to: "pets#new", as: "new_pet"
  post "/pets", to: "pets#create"
  get "/pets/:id", to: "pets#show", as: "pet"
  get "/pets/:id/edit", to: "pets#edit", as: "edit_pet"
  put "/pets/:id", to: "pets#update"
  patch "/pets/:id", to: "pets#update"
  delete "/pets/:id", to: "pets#destroy"  

  get "/bookings", to: "bookings#index", as: "bookings"
  get "/petsitters/:id/bookings/new", to: "bookings#new", as: "new_booking"
  post "/bookings", to: "bookings#create"
  get "/bookings/:id", to: "bookings#show", as: "booking"
  patch "/bookings/:id/accept", to: "bookings#accept", as: "accept_booking"
  patch "/bookings/:id/reject", to: "bookings#reject", as: "reject_booking"
  get "/bookings/:id/success", to: "bookings#success", as: "success_booking"
  post "/bookings/webhook", to: "bookings#webhook", as: "complete_booking"

  get "/petsitters", to: "petsitters#index", as: "petsitters"
  get "/petsitters/new", to: "petsitters#new", as: "new_petsitter"
  post "/petsitters", to: "petsitters#create"
  get "/petsitters/:id", to: "petsitters#show", as: "petsitter"
  get "/petsitters/:id/edit", to: "petsitters#edit", as: "edit_petsitter"
  put "/petsitters/:id", to: "petsitters#update"
  patch "/petsitters/:id", to: "petsitters#update"
  delete "/petsitters/:id", to: "petsitters#destroy"

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :petsitter
  has_many :bookings_pets, dependent: :destroy
  has_many :pets, through: :bookings_pets
  enum status: { pending: 0, accepted: 1, rejected: 2, completed: 3}
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    protect_from_forgery except: [:webhook]
    before_action :authenticate_user!, except: [:webhook]
    before_action :set_booking, only: [:show, :accept, :reject, :success]

    def index
        # Retrieving from the Database all the bookings involving to the logged-in user.
        # The logged in user can either be the pet-owner (first where condition) or the pet-sitter (second where condition)
        @bookings = Booking.where(user_id: current_user.id).or(Booking.where(petsitter_id: current_user.petsitter))
    end

    def show

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: "Pet-BnB booking",
                description: "#{@booking.petsitter.user.first_name} #{@booking.petsitter.user.last_name}' services",
                images: [url_for(@booking.petsitter.user.picture)],
                amount: @booking.total_amount,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    booking_id: @booking.id,
                    petsitter_id: @booking.petsitter_id,
                    total_amount: @booking.total_amount
                }
            },
            success_url: "#{root_url}bookings/#{@booking.id}/success",
            cancel_url: "#{root_url}bookings"
        )

        @session_id = session.id

    end

    def new

        # Assigning @booking the "shape" of the Booking active record. No real data is retrieved 
        @booking = Booking.new
        # Assigning @petsitter with the specific Petsitter record ID 
        @petsitter = Petsitter.find(params[:id].to_i)
        # Manually populating foreign keys
        @booking.petsitter_id = @petsitter.id
        # Retrieving an array of Pets Active Records
        @pets = Pet.where(user_id: current_user.id)

    end

    def accept

        # Validating input requests; an accepted booking can only be processed if the status of the booking was pending
        if @booking.status == Booking.statuses.keys[0] &&
           @booking.petsitter_id = current_user.petsitter.id

           # Processing the booking with the next status code
           @booking.status = Booking.statuses.keys[1]

           # Applying/Updating the new status code to the database
           @booking.save
        end

        redirect_to booking_path(@booking.id)

    end

    def reject

        # Validating input requests; a rejection on a booking can only be processed if the status of the booking was either pending or waiting for payment
        if ( @booking.status == Booking.statuses.keys[0] || 
             @booking.status == Booking.statuses.keys[1] ) &&
           ( @booking.user_id == current_user.id || 
             @booking.petsitter_id == current_user.petsitter.id
           )
           
            # Processing the booking with the next status code
            @booking.status = Booking.statuses.keys[2]

            # Applying/Updating the new status code to the database
            @booking.save
         end

        redirect_to booking_path(@booking.id)

    end

    def webhook

        head 200

        stripe_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(stripe_id)

        booking_id = payment.metadata.booking_id
        petsitter_id = payment.metadata.petsitter_id
        user_id = payment.metadata.user_id
        total_amount = payment.metadata.total_amount

        # Retrieving from the database the exact record corresponding to the booking received by Stripe
        booking = Booking.find_by_id(booking_id)

        # Checking if an active record was found
        if booking
            puts "WEBHOOK: A booking record with id=#{booking_id} was found!"

            if booking.petsitter_id.to_s == petsitter_id.to_s &&
               booking.user_id.to_s == user_id.to_s &&
               booking.total_amount.to_s == total_amount.to_s

                puts "WEBHOOK: All attributes match!"

                # Marking the active record as Completed
                booking.status = Booking.statuses.keys[3]
                booking.stripe_id = stripe_id

                # Updating the database
                booking.save

            else
                puts "WEBHOOK: ERROR, Attributes do not match!"

                p petsitter_id
                p user_id
                p total_amount

                p booking.petsitter_id
                p booking.user_id
                p booking.total_amount

            end
        else
            puts "WEBHOOK: ERROR, No booking record found!"

        end

    end

    def success

        redirect_to booking_path(@booking.id)

    end

    def create

        whitelisted_params = booking_params
        whitelisted_params.merge!(user_id: current_user.id)

        # Retrieving the Petsitter record involved with the request (received by the View)
        petsitter = Petsitter.find(params[:booking][:petsitter_id])
        total_amount = (params[:booking][:to_date].to_date - params[:booking][:from_date].to_date).to_i * petsitter.price_rate
       
        # Adding extra field to the whitelisted fields
        whitelisted_params.merge!(total_amount: total_amount)

        # Adding extra field to the whitelisted fields
        whitelisted_params.merge!(status: Booking.statuses.keys[0])
        
        # Saving/applying the new record on the Bookings table
        # By using "current_user" as first element, I get for free all the FK required
        @booking = current_user.bookings.create(whitelisted_params)

        if @booking.errors.any?
            render "new"
        else
            redirect_to booking_path(@booking)
        end
    end

    private

    private

    def booking_params
        params.require(:booking).permit(:from_date, :to_date, :petsitter_id, pet_ids: [])
    end

    def set_booking
        # Retrieving from the Database the required Booking ID (passed by the View)
        @booking = Booking.find(params[:id])
    end

end

app/views/bookings/_form.html.erb
<% if booking.errors.any? %>

    <% for error in booking.errors.full_messages %>
        <p><%=error%></p>
    <% end %>

<% end %>

<%= form_with model: booking, local: true, class: "reserve-booking" do |form| %>

    <div class="picture-container">

        <% if petsitter.user.picture.attached? %>
            <%= image_tag petsitter.user.picture, id:"picture-preview" %>
        <% end %>

    </div>    

    <%= form.hidden_field :petsitter_id, value: @petsitter.id %>

    <%= form.label :from_date %>
    <%= form.date_field :from_date %>

    <%= form.label :to_date %>
    <%= form.date_field :to_date %>

    <%= form.label :"pets_to_include:" %>
    <div class="checkbox-list">
        <%= form.collection_check_boxes :pet_ids, pets, :id, :name %>
    </div>

    <%= form.submit class: "link-button" %>

<% end %>

app/views/bookings/index.html.erb
<main id="booking" class="container">

    <h2 class="page-name">Bookings you requested</h2>

    <table class="form">
        <thead>
            <tr>
                <th class="icon-column">Status</th>
                <th class="split-column">Dates</th>
                <th>Petsitter</th>
            </tr>
        </thead>
        <tbody>
            <% @bookings.each_with_index do |booking, index| %>
                <% if booking.user_id == current_user.id %>

                    <tr onclick="document.location='<%= booking_path(booking)%>'" style="cursor:pointer">
                        <td class="icon-column">
                            <% case booking.status %>
                                <% when Booking.statuses.keys[0] %>
                                    <%= image_tag "booking/pending.png", class:"booking-icon-status", alt:"Pending request" %>
                                <% when Booking.statuses.keys[1] %>
                                    <%= image_tag "booking/accepted.png", class:"booking-icon-status", alt:"Request accepted" %>
                                <% when Booking.statuses.keys[2] %>
                                    <%= image_tag "booking/rejected.png", class:"booking-icon-status", alt:"Request rejected" %>
                                <% when Booking.statuses.keys[3] %>
                                    <%= image_tag "booking/completed.png", class:"booking-icon-status", alt:"Request completed" %>
                            <% end %>
                        </td>
                        <td>
                            <p><%= booking.from_date %></p>
                            <p><%= booking.to_date %></p>
                            
                        </td>
                        <td><%= booking.petsitter.user.first_name %></td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3"></th>
            </tr>
        </tfoot>
    </table>

    <h2 class="page-name">Bookings requested to you</h2>

    <table class="form">
        <thead>
            <tr>
                <th class="icon-column">Status</th>
                <th class="split-column">Dates</th>
                <th>Petowner</th>
            </tr>
        </thead>
        <tbody>
            <% @bookings.each_with_index do |booking, index| %>

                <% if current_user.petsitter && booking.petsitter_id == current_user.petsitter.id %>

                    <tr onclick="document.location='<%= booking_path(booking)%>'" style="cursor:pointer">
                        <td class="icon-column">
                            <% case booking.status %>
                                <% when Booking.statuses.keys[0] %>
                                    <%= image_tag "booking/pending.png", class:"booking-icon-status", alt:"Pending request" %>
                                <% when Booking.statuses.keys[1] %>
                                    <%= image_tag "booking/accepted.png", class:"booking-icon-status", alt:"Request accepted" %>
                                <% when Booking.statuses.keys[2] %>
                                    <%= image_tag "booking/rejected.png", class:"booking-icon-status", alt:"Request rejected" %>
                                <% when Booking.statuses.keys[3] %>
                                    <%= image_tag "booking/completed.png", class:"booking-icon-status", alt:"Request completed" %>
                            <% end %>
                        </td>
                        <td>
                            <p><%= booking.from_date %></p>
                            <p><%= booking.to_date %></p>
                            
                        </td>
                        <td><%= booking.user.first_name %></td>
                    </tr>

                <% end %>

            <% end %>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3"></th>
            </tr>
        </tfoot>
    </table>

</main>

app/views/bookings/new.html.erb
<main id="booking" class="container">

    <h2 class="page-name">Place a Booking</h2>

    <%= render "form", booking: @booking, petsitter: @petsitter, pets: @pets %>

</main>

app/views/bookings/show.html.erb
<main id="booking" class="container">

    <h2 class="page-name">Booking details</h2>

    <table class="form">
        <thead>
            <tr>
                <th>Info</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="half-column">Booking ID</td>
                <td class="half-column"><%=@booking.id.to_s.rjust(5, '0')%></td>
            </tr>
            <tr>
                <td class="half-column">From Date</td>
                <td class="half-column"><%=@booking.from_date%></td>
            </tr>
            <tr>
                <td class="half-column">To Date</td>
                <td class="half-column"><%=@booking.to_date%></td>
            </tr>
            <tr>
                <td class="half-column">Request Status</td>
                <td class="half-column"><%=@booking.status%></td>
            </tr>
            <tr>
                <td class="half-column">Icon Status</td>
                <td class="half-column icon-column">
                    <% case @booking.status %>
                        <% when Booking.statuses.keys[0] %>
                            <%= image_tag "booking/pending.png", class:"booking-icon-status", alt:"Pending request" %>
                        <% when Booking.statuses.keys[1] %>
                            <%= image_tag "booking/accepted.png", class:"booking-icon-status", alt:"Request accepted" %>
                        <% when Booking.statuses.keys[2] %>
                            <%= image_tag "booking/rejected.png", class:"booking-icon-status", alt:"Request rejected" %>
                        <% when Booking.statuses.keys[3] %>
                            <%= image_tag "booking/completed.png", class:"booking-icon-status", alt:"Request completed" %>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td class="half-column">Total Amount</td>
                <td class="half-column"><%=number_to_currency(@booking.total_amount/100.0)%></td>
            </tr>
            <tr>
                <td class="half-column">Pet Owner</td>
                <td class="half-column"><%=@booking.user.first_name%></td>
            </tr>
            <tr>
                <td class="half-column">Pet Sitter</td>
                <td class="half-column"><%=@booking.petsitter.user.first_name%></td>
            </tr>

        </tbody>
    </table>

    <% case @booking.status %>
        <% when Booking.statuses.keys[0] %>

            <% if current_user.petsitter && @booking.petsitter_id == current_user.petsitter.id %>
                <%= link_to "Accept", accept_booking_path(@booking.id), method: :patch, data: { confirm: 'Are you sure?' }, class: "link-button"%>
            <% end %>
            <%= link_to "Reject", reject_booking_path(@booking.id), method: :patch, data: { confirm: 'Are you sure?' }, class: "link-button"%>    

        <% when Booking.statuses.keys[1] %>
            
            <% if @booking.user_id == current_user.id %>
                <button id="pay-button" class="link-button">Pay</button>
            <% end %>
            <%= link_to "Reject", reject_booking_path(@booking.id), method: :patch, data: { confirm: 'Are you sure?' }, class: "link-button"%>    
    
    <% end %>

</main>

<script>

    document.getElementById("pay-button").addEventListener("click", () => {

        if (confirm('Are you sure?')) {
            const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
            stripe.redirectToCheckout({
                sessionId: "<%= @session_id %>"
            })
        }

    })

</script>